# Generated by Django 5.1.5 on 2025-03-26 07:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('races', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='car',
            name='images_folder',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
