# Generated by Django 5.1.5 on 2025-03-29 20:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('races', '0002_car_images_folder'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='raceparticipant',
            unique_together={('race', 'car')},
        ),
    ]
