# Generated by Django 5.1.5 on 2025-04-09 19:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('races', '0003_alter_raceparticipant_unique_together'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='race',
            name='join_code',
        ),
        migrations.AddField(
            model_name='car',
            name='is_eligible',
            field=models.BooleanField(default=False),
        ),
    ]
