# Generated by Django 5.1.5 on 2025-03-27 20:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='cognitouser',
            name='cognito_identity_id',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
