# Generated by Django 5.1.5 on 2025-02-17 18:48

import media.models
import webapp.storages
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('media', '0003_remove_image_user_image_username_alter_image_image'),
    ]

    operations = [
        migrations.CreateModel(
            name='Video',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(default='default_user', max_length=255)),
                ('race', models.CharField(max_length=255)),
                ('title', models.CharField(max_length=255)),
                ('file', models.FileField(storage=webapp.storages.RacesBucketStorage(), upload_to=media.models.video_upload_to)),
                ('thumbnail', models.ImageField(blank=True, null=True, storage=webapp.storages.RacesBucketStorage())),
                ('upload_time', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
