# Generated by Django 5.1.5 on 2025-02-19 15:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('media', '0004_video'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='video',
            name='thumbnail',
        ),
        migrations.RemoveField(
            model_name='video',
            name='title',
        ),
        migrations.RemoveField(
            model_name='video',
            name='username',
        ),
    ]
