# Generated by Django 5.1.5 on 2025-03-26 07:59

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('media', '0005_remove_video_thumbnail_remove_video_title_and_more'),
        ('races', '0002_car_images_folder'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='image',
            name='car_name',
        ),
        migrations.RemoveField(
            model_name='image',
            name='username',
        ),
        migrations.AddField(
            model_name='image',
            name='car',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='images', to='races.car'),
        ),
    ]
